ManagementWebApplication/Pages/Employee/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ManagementWebApplication.Models;
using ManagementWebApplication.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ManagementWebApplication.Pages.Employee
{
    public class CreateModel : PageModel
    {
        private readonly EmployeeService ServiceMan;

        public CreateModel(EmployeeService employeeService)
        {
            this.ServiceMan = employeeService;
        }

        [BindProperty]
        public EmployeeModel NewEmployee { set; get; }
        public void OnGet()
        {
        }

        public async Task<IActionResult> OnPost()
        {
            if(ModelState.IsValid == false)
            {
                return Page();
            }

            await ServiceMan.InsertEmployee(NewEmployee);
            return Redirect("./");
        }
    }
}

ManagementWebApplication/Pages/Employee/CreateApp.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ManagementWebApplication.Models;
using ManagementWebApplication.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ManagementWebApplication.Pages.Employee
{
    public class CreateAppModel : PageModel
    {
        private readonly EmployeeAppService _serviceMan;

        [BindProperty]
        public EmployeeModelApp NewEmployeeApp { set; get; }


        public CreateAppModel(EmployeeAppService employeeAppService)
        {
            this._serviceMan = employeeAppService;
        }
        public void OnGet(Guid id)
        {
            NewEmployeeApp = new EmployeeModelApp();
            //buat masukkin employeeID ke textbox yang kita hidden
            NewEmployeeApp.EmployeeId = id;
        }
        public async Task<IActionResult> OnPost()
        {
            if(ModelState.IsValid == false)
            {
                return Page();
            }
            await _serviceMan.InsertNewEmployeeApp(NewEmployeeApp);
            return Redirect("/Employee");
        }
    }
}

ManagementWebApplication/Pages/Employee/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using ManagementWebApplication.Models;
using ManagementWebApplication.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ManagementWebApplication.Pages.Employee
{
    public class IndexModel : PageModel
    {
        private readonly EmployeeService ServiceMan;

        public IndexModel(EmployeeService employeeService)
        {
            this.ServiceMan = employeeService;
        }

        public List<EmployeeModel> Employees { set; get; }

        // For filter 
        [Display(Name = "Search")]
        [BindProperty(SupportsGet = true)]
        public string FilterByName { get; set; }

        public int TotalPage { set; get; }
        [BindProperty(SupportsGet = true)]
        public int PageIndex { set; get; }
        public int ItemPerPage => 5;

        public async Task OnGetAsync()
        {
            if(PageIndex == 0)
            {
                PageIndex = 1;
            }

            // add param filterByName for filtering
            Employees = await ServiceMan.GetAsync(PageIndex, ItemPerPage, FilterByName);

            var totalEmployee = ServiceMan.GetTotalData();

            TotalPage = (int)Math.Ceiling(totalEmployee / (double)ItemPerPage);
        }

        public async Task<IActionResult> OnPostDeleteAsync(Guid id)
        {
            var isSuccess = await this.ServiceMan.DeleteEmployeeAsync(id);

            if (isSuccess == false)
            {
                return Page();
            }
            return Redirect("/employee");
        }
    }
}

ManagementWebApplication/Pages/Employee/IndexApp.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ManagementWebApplication.Models;
using ManagementWebApplication.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ManagementWebApplication.Pages.Employee
{
    public class IndexAppModel : PageModel
    {
        private readonly EmployeeAppService _serviceMan;
        public Guid IdEmployee { get; set; }

        public IndexAppModel(EmployeeAppService employeeAppService)
        {
            this._serviceMan = employeeAppService;
        }

        public List<EmployeeModelApp> employeeModelApps;
        public async Task OnGetAsync(Guid id)
        {
            this.employeeModelApps = await this._serviceMan.GetAsync(id);
            IdEmployee = id;
        }
        public async Task<IActionResult> OnPostDeleteAsync (int id)
        {
            var isSuccess = await this._serviceMan.DeleteApp(id);
            if(isSuccess==false)
            {
                return Page();
            }
            return Redirect("/Employee/Index");
           
        }

        
    }
}

ManagementWebApplication/Pages/Employee/Update.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ManagementWebApplication.Models;
using ManagementWebApplication.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ManagementWebApplication.Pages.Employee
{
    public class UpdateModel : PageModel
    {
        private readonly EmployeeService ServiceMan;

        public UpdateModel(EmployeeService employeeService)
        {
            this.ServiceMan = employeeService;
        }

        [BindProperty]
        public EmployeeModel CurrentEmployee { set; get; }

        public async Task OnGetAsync(Guid id)
        {
            CurrentEmployee = await ServiceMan.GetSpesificEmployeeAsync(id);
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (ModelState.IsValid == false)
            {
                return Page();
            }

            var isExist = await ServiceMan.UpdateEmployeeAsync(CurrentEmployee);

            if(isExist == false)
            {
                return Page();
            }
            return Redirect("/employee");
        }
    }
}

ManagementWebApplication/Pages/Employee/UpdateApp.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ManagementWebApplication.Models;
using ManagementWebApplication.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ManagementWebApplication.Pages.Employee
{
    public class UpdateAppModel : PageModel
    {
        private readonly EmployeeAppService _serviceApp;
        [BindProperty]
        public EmployeeModelApp CurrentApp { get; set; }

        public UpdateAppModel(EmployeeAppService employeeAppService)
        {
            this._serviceApp = employeeAppService;
        }

        public async Task OnGet(int id)
        {
            CurrentApp = await _serviceApp.GetSpecificAppAsync(id);

        }

        public async Task<IActionResult> OnPostAsync() {
            if (ModelState.IsValid == false)
            {
                return Page();
            }
            var isExist = await _serviceApp.UpdateAppAsync(CurrentApp);

            if(isExist == false)
            {
                return Page();
            }

            return Redirect("/employee/IndexApp");
        
        }


    }
}

ManagementWebApplication/Pages/Workplace/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ManagementWebApplication.Models;
using ManagementWebApplication.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ManagementWebApplication.Pages.Workplace
{
    public class CreateModel : PageModel
    {
        private readonly WorkplaceService WorkplaceService;

        public CreateModel(WorkplaceService workplaceService)
        {
            this.WorkplaceService = workplaceService;
        }

        [BindProperty]
        public CreateWorkplaceModel CreateWorkplaceForm { get; set; }

        public void OnGet()
        {
        }

        public async Task<ActionResult> OnPostAsync()
        {
            if (ModelState.IsValid == false)
            {
                // Using TempData, you can pass the value to the Razor Page.
                // Reference: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/app-state?view=aspnetcore-3.1.
                TempData["ErrorMessage"] = "Data is invalid.";
                return Page();
            }

            await this.WorkplaceService.CreateAsync(this.CreateWorkplaceForm);

            TempData["Message"] = "Successfully added the new data";
            return RedirectToPage();
        }
    }
}

ManagementWebApplication/Pages/Employee/Create.cshtml
@page
@model ManagementWebApplication.Pages.Employee.CreateModel
@{
}
    <form method="post">
        <label class="col-form-label" asp-for="NewEmployee.Name"></label>
        <input type="text" asp-for="NewEmployee.Name" class="form-control" />
        <span asp-validation-for="NewEmployee.Name" class="text-danger"></span>
        <br />
        <label class="col-form-label" asp-for="NewEmployee.Email"></label>
        <input type="text" asp-for="NewEmployee.Email" class="form-control" />
        <span asp-validation-for="NewEmployee.Email" class="text-danger"></span>
        <br />
        <label class="col-form-label" asp-for="NewEmployee.PhoneNumber"></label>
        <input type="text" asp-for="NewEmployee.PhoneNumber" class="form-control" />
        <span asp-validation-for="NewEmployee.PhoneNumber" class="text-danger"></span>
        <br />
        <button type="submit" class="btn btn-primary">
            Submit
        </button>
    </form>

ManagementWebApplication/Pages/Employee/CreateApp.cshtml
@page "{id}"
@model ManagementWebApplication.Pages.Employee.CreateAppModel
@{
}

    <form method="post">
        <input type="text" asp-for="NewEmployeeApp.EmployeeId" class="form-control" hidden />

        <label class="col-form-label" asp-for="NewEmployeeApp.Name"></label>
        <input type="text" asp-for="NewEmployeeApp.Name" class="form-control" />
        <span asp-validation-for="NewEmployeeApp.Name" class="text-danger"></span>
        <br />
        <label class="col-form-label" asp-for="NewEmployeeApp.Url"></label>
        <input type="text" asp-for="NewEmployeeApp.Url" class="form-control" />
        <span asp-validation-for="NewEmployeeApp.Url" class="text-danger"></span>
        <br />
        <label class="col-form-label" asp-for="NewEmployeeApp.CreatedBy"></label>
        <input type="text" asp-for="NewEmployeeApp.CreatedBy" class="form-control" />
        <span asp-validation-for="NewEmployeeApp.CreatedBy" class="text-danger"></span>
        <br />
        <button type="submit" class="btn btn-primary">
            Submit
        </button>
    </form>

ManagementWebApplication/Pages/Employee/Index.cshtml
@page
@model ManagementWebApplication.Pages.Employee.IndexModel
@{
}
<list-employee></list-employee>
@*<form method="get">
            <div>
                <div>
                    <label asp-for="FilterByName">
                    </label>
                    <div class="col-md-5">
                        <input asp-for="FilterByName" />
                    </div>
                    <div class="col-md-2">
                        <button type="submit"
                                class="btn btn-block btn-primary">
                            Search
                        </button>
                    </div>
                </div>
            </div>
        </form>
    <div class="row">
        <div class="col-md-12">
            <div class="table-responsive">
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th>No</th>
                            <th>Name</th>
                            <th>Email</th>
                            <th>Phone Number</th>
                        </tr>
                    </thead>
                    <tbody>
                        @{
                            var i = 1;
                            foreach (var employee in Model.Employees)
                            {
                                <tr>
                                    <td>@(((Model.PageIndex-1)*Model.ItemPerPage)+i)</td>
                                    <td>@employee.Name</td>
                                    <td>@employee.Email</td>
                                    <td>@employee.PhoneNumber</td>
                                    <td>
                                        <div class="row">
                                            <div class="col-md-3">
                                                <a asp-page="./update" asp-route-Id="@employee.EmployeeId" class="btn btn-warning">Edit</a>
                                            </div>
                                            <div class="col-md-3">
                                                <form method="post" asp-page-handler="delete" asp-route-Id="@employee.EmployeeId">
                                                    <button type="submit" class="btn btn-danger">
                                                        Delete
                                                    </button>
                                                </form>
                                            </div>
                                            <div class="col-md-3">
                                                <a asp-page="./IndexApp" asp-route-Id="@employee.EmployeeId" class="btn btn-info">Details</a>
                                            </div>
                                        </div>
                                    </td>
                                </tr>
                                i += 1;
                            }
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <ul class="pagination">
                @{
                    for (var j = 1; j <= Model.TotalPage; j++)
                    {
                        var activeClass = j == Model.PageIndex ? "active" : "";
                        <li class="page-item @activeClass">
                            <a asp-route-PageIndex="@j" class="page-link">@j</a>
                        </li>
                    }
                }
            </ul>
        </div>
    </div>*@

ManagementWebApplication/Pages/Employee/IndexApp.cshtml
@page
@model ManagementWebApplication.Pages.Employee.IndexAppModel
@{
}

<list-employee-app></list-employee-app>
@*<table class="table table-bordered">
    <thead>
        <tr>
            <th>No</th>
            <th>Name</th>
            <th>Url</th>
            <th>
                <a asp-page="./CreateApp" asp-route-id="@Model.IdEmployee" class="btn btn-info">Create</a>
            </th>
        </tr>
    </thead>
    <tbody>
        @{
            var i = 1;
            foreach (var employeeApps in Model.employeeModelApps)
            {
                <tr>
                    <td>@i</td>
                    <td>@employeeApps.Name</td>
                    <td>@employeeApps.Url</td>
                    <td>
                        <table class="table-borderless">
                            <tr>
                                <td><a asp-page="./UpdateApp" asp-route-Id="@employeeApps.EmployeeAppId">Edit</a></td>
                                <td> <form method="post" asp-page-handler="Delete" asp-route-Id="@employeeApps.EmployeeAppId">
                                         <button type="submit" class="btn btn-danger">Delete</button>
                                     </form></td>
                            </tr>
                        </table>
                    </td>
                </tr>
                i++;
            }
        }
    </tbody>
</table>*@

ManagementWebApplication/Pages/Employee/Update.cshtml
@page
@model ManagementWebApplication.Pages.Employee.UpdateModel
@{
}
<update-employee></update-employee>
    @*<form method="post">
        <input type="text" asp-for="CurrentEmployee.EmployeeId" hidden />

        <label class="col-form-label" asp-for="CurrentEmployee.Name"></label>
        <input type="text" asp-for="CurrentEmployee.Name" class="form-control" />
        <span asp-validation-for="CurrentEmployee.Name" class="text-danger"></span>
        <br />
        <label class="col-form-label" asp-for="CurrentEmployee.Email"></label>
        <input type="text" asp-for="CurrentEmployee.Email" class="form-control" />
        <span asp-validation-for="CurrentEmployee.Email" class="text-danger"></span>
        <br />
        <label class="col-form-label" asp-for="CurrentEmployee.PhoneNumber"></label>
        <input type="text" asp-for="CurrentEmployee.PhoneNumber" class="form-control" />
        <span asp-validation-for="CurrentEmployee.PhoneNumber" class="text-danger"></span>
        <br />
        <button type="submit" class="btn btn-primary">
            Submit
        </button>
    </form>*@

ManagementWebApplication/Pages/Employee/UpdateApp.cshtml
@page
@model ManagementWebApplication.Pages.Employee.UpdateAppModel
@{
}
    
<update-employee-app></update-employee-app>
    @*<form method="post">
        <input type="text" asp-for="CurrentApp.EmployeeAppId" hidden />

        <label class="col-form-label" asp-for="CurrentApp.Name"></label>
        <input type="text" asp-for="CurrentApp.Name" class="form-control" />
        <span asp-validation-for="CurrentApp.Name" class="text-danger"></span>
        <br />

        <label class="col-form-label" asp-for="CurrentApp.Url"></label>
        <input type="text" asp-for="CurrentApp.Url" class="form-control" />
        <span asp-validation-for="CurrentApp.Url" class="text-danger"></span>
        <br />

        <label class="col-form-label" asp-for="CurrentApp.UpdatedBy"></label>
        <input type="text" asp-for="CurrentApp.UpdatedBy" class="form-control" />
        <span asp-validation-for="CurrentApp.UpdatedBy" class="text-danger"></span>
        
        <br />
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>*@